# This file was generated by GoReleaser. DO NOT EDIT.
cask "dibs" do
  app "Dibs.app"

  version "0.0.7"

  on_macos do
    on_arm do
      sha256 "4e1fedac0370b4d60ca29d0c8b3e24adfeef2736046e666a324e67877bbd3f0b"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f87de1c85ddc7aa122330e53aa7e3cebc4c5a90c7f23495822e74d102ca6cf25"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fc3efb7e32d908406ee5a94fa4f900edfc3d34e3cee3e40c3fd4f0117ef0a9a5"
      url "https://github.com/Agenxy/dibs/releases/download/v#{version}/dibs_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dibs"
  desc "Coordination and situational-awareness board for fleets of AI agents"
  homepage "https://github.com/agenxy/dibs"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dibs"
  binary "dibd"
  binary "dibs-presence"
  manpage "dibd.8"
  manpage "dibs.1"

  postflight do
    system_command "/usr/bin/xattr",
                   args:         ["-dr", "com.apple.quarantine", staged_path.to_s],
                   # NOT fatal, and the caveats say so rather than
                   # claiming this always works. xattr exits non-zero in
                   # ordinary cases, including having no such attribute to
                   # remove, so failing the install over it would be worse
                   # than the warning it prevents. What was wrong was the
                   # caveat asserting the flag IS cleared while this could
                   # silently not clear it: an operator then meets a
                   # "developer cannot be verified" dialog that the
                   # documentation says is impossible.
                   must_succeed: false
  end

  # No zap stanza required

  caveats <<~EOS
    Start the daemon and point your agents at it:

      dibd &                  # 127.0.0.1:4777, data in ~/.dibs
      dibs mcp-config          # MCP config to add to your harness
      dibs web                 # the board; Touch ID unlocks it on this Mac
      dibs doctor              # what is quietly broken, and how to fix it

    Signed for provenance with cosign, but not notarised by Apple, so this
    cask TRIES to clear the quarantine flag on install. It is not treated as
    fatal: `xattr` exits non-zero in ordinary cases, including when there is
    no such attribute to remove, and failing the install over that would be
    worse than the warning it prevents.

    So if macOS still says the developer cannot be verified, it did not work
    and you can finish it by hand:

      xattr -dr com.apple.quarantine "$(brew --prefix)/bin/dibd" "$(brew --prefix)/bin/dibs"
  EOS
end
